version: '3.7'
services:
  hello-app:
    build: .
    ports:
      - 3000:3000
      - 9000:9000
    env_file: ./environments/.env
    volumes:
      - ./:/usr/src/app:delegated
    command: "start:dev"
    restart: always
