version: '3.7'
services:
  hello-app:
    build: .
    ports:
      - 3000:3000
      - 9000:9000
    environment: 
      - HOST=localhost
      - PORT=3000
      - KUBERNETES_SERVICE_HOST=true
    volumes:
      - ./:/usr/src/app:delegated
    command: "start:dev"
    restart: always
