version: '3.7'
services:
  hello-app:
    image: node:12.14
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app:delegated
    entrypoint: sh -c "yarn global add typescript && yarn --prod=false"