version: '3.7'
services:

  hello-app:
    image: eji4h/dks-hello-world-app:1.0.0
    restart: always
    environment: 
      - HOST=localhost
      - PORT=3000
      - KUBERNETES_SERVICE_HOST=true
    ports:
      - 3000:3000
      - 9000:9000